---
- hosts: "{{svrs}}"
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: copy template server.config.js.j2 to /home/root/app/storyboard/source/storyboard/config/server.config.js
      template: src=server.config.js.j2 dest=/home/root/app/storyboard/source/config/server.config.js
